Задача 1. Инициализация рабочего окружения
RoketFlame/formal-lang-course pull request #1
Opened 2024-09-09 20:57 UTC by RoketFlame

* [x]  Сделать `fork` данного репозитория.
 * [x]  Добавить ссылку на ваш `fork` в [таблицу](https://docs.google.com/spreadsheets/d/1X7Hx6IyltD_NyTTphyzbN74Ag-G_LDzUu4OGcHoI8tg/edit?usp=sharing).
 * [x]  Добавить в совладельцы форка одного из ассистентов (чтобы узнать, кого именно, нужно посмотреть в таблицу)
 * [x]  Реализовать модуль, предоставляющий перечисленные ниже возможности. Для работы с графами использовать [cfpq-data](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/tutorial.html#graphs). Данный модуль в дальнейшем будет расширяться. Функции, которые необходимо реализовать:
   
   * [x]  По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах. Для получения графа по имени использовать [эту функцию](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/tutorial.html#load-graph).
   * [x]  По количеству вершин в циклах и именам меток строить [граф из двух циклов](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.generators.labeled_two_cycles_graph.html#cfpq_data.graphs.generators.labeled_two_cycles_graph) и сохранять его в указанный файл в формате DOT (использовать pydot).
 * [x]  Добавить необходимые тесты.

2024-09-10 07:55 UTC, WoWaster requested changes
Если это попытка обойти систему, то ну такое себе. Но шанс реабилитироваться, объяснив, что это было, пока есть

2024-09-12 21:25 UTC, RoketFlame commented
> Если это попытка обойти систему, то ну такое себе. Но шанс реабилитироваться, объяснив, что это было, пока есть

Я не совсем понимаю, о чем конкртено идет речь. Если это про время сдачи самой работы, то я просто забыл отправить решение и вспомнил об этом только в последний час дедлайна

2024-09-13 07:13 UTC, WoWaster commented
Правила сдачи задач указывают на три вещи:
1) Единица проверки работы --- запрос ревью.
2) За коммиты после запроса ревью максимально возможный балл уменьшается вдвое.
3) Временем сдачи считается запрос ревью.

Здесь я наблюдаю следующее: ситуацию запрос-отмена-запрос ревью, а также коммиты между. 
Если действовать по всем правилам, то я вообще должен данную ситуацию считать как трату одной попытки сдачи даже без ревью от проверяющего, уменьшить максимальный балл в два раза за коммит после запроса ревью, и ещё в два раза уменьшить, за просроченный дедлайн. Итого 5/4 = 1.25 балла. 

Звучит как-то жестоко. Поэтому пока что предлагаю объяснить что случилось, и были ли какие-то не зависящие от тебя проблемы со сдачей, типа выключенных в форке GitHub Actions.

2024-09-13 08:46 UTC, RoketFlame commented
> Правила сдачи задач указывают на три вещи:
> 
> 1. Единица проверки работы --- запрос ревью.
> 2. За коммиты после запроса ревью максимально возможный балл уменьшается вдвое.
> 3. Временем сдачи считается запрос ревью.
> 
> Здесь я наблюдаю следующее: ситуацию запрос-отмена-запрос ревью, а также коммиты между. Если действовать по всем правилам, то я вообще должен данную ситуацию считать как трату одной попытки сдачи даже без ревью от проверяющего, уменьшить максимальный балл в два раза за коммит после запроса ревью, и ещё в два раза уменьшить, за просроченный дедлайн. Итого 5/4 = 1.25 балла.
> 
> Звучит как-то жестоко. Поэтому пока что предлагаю объяснить что случилось, и были ли какие-то не зависящие от тебя проблемы со сдачей, типа выключенных в форке GitHub Actions.

Да, actions были выключены при создании PR, поэтому пришлось сделать коммит и я тут же его убрать. Так как время совсем поджимало, я не глядя еще раз запросил ревью, так как не был уверен, что новые коммиты не отменят ревью

2024-09-13 10:24 UTC, WoWaster approved these changes
Будем считать, что прокатило

2024-09-16 13:29 UTC, merged